postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: Karan
    POSTGRES_PASSWORD:
  ports:
    - '5432:5432'
  volumes:
    - pinit-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - pinit-redis:/var/lib/redis/data

pinit:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/pinit
  ports:
    - '8000:8000'
  env_file:
    - .pinit.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/pinit
  env_file:
    - .pinit.env
