# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 521e0ea0b03f4dd4ba8e4adfc5b4adeba551f5279c356edd2d24235814790c56acefda2e3970485901cb2b24f83f52f52199a276de45c22b42bb6a05ff19705d

test:
  secret_key_base: 071bb149a86725e830efb3b4a1a8bfb2a96b4f03025a22d0ee022ace0bf976d2d77d5c2e39f6cb151b11023c0ea41228d574ba63598f190b7eaab28eb56dd534

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
